version: "3.7"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: automated-barnacle
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"


networks:
  backend:

